# Site settings
title: Le Penon Surf House
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://lepenon-surfhouse.fr" # the base hostname & protocol for your site

# Contact Information
email: camille@madamekeys.com
phone_number: 0033682185951
phone_display: "+33 (0)6 82 18 59 51"
github_link: "kevindelord/lepenon-surfhouse"

# Postal Address
rental_residence: "Résidence Atlantique, Apt. 5"
rental_streetAddress: "9 Avenue Chambrelent"
rental_addressLocality: "Seignosse"
rental_postalCode: "40510"
rental_addressCountry: "France"
rental_geo_latitude: 43.7121658
rental_geo_longitude: -1.4314518

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap

sass:
  compressed: true

exclude: ['scripts', 'README.md', 'LICENSE']

collections:
  languages:
    output: false
  images:
    output: false

permalink: pretty
