# Site settings
title: Le Penon Surf House
description: surf house beach> # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "lepenon-surfhouse.fr" # the base hostname & protocol for your site

# Contact Information
email: delord.kevin@gmail.com
phone_number: 0033558123456
phone_display: "+33 (0)5 58 12 34 56"

# Build settings
markdown: kramdown

sass:
  compressed: true

include: ['_activities', '_services', '_languages', '_images']
exclude: ['scripts', 'README.md', 'LICENSE']

collections:
  activities:
    output: false
  services:
    output: false
  languages:
    output: false
  images:
    output: false

permalink: pretty
